name: LightBikes
main: com.ksanur.lightbikes.LightBikes
version: ${version}
description: LightBikes minigame
author: bobacadodl
depend: [SQLibrary]
commands:
  lightbikes:
    description: LightBikes main command
    aliases: [tron, lightbike, lb]